---
title: "tutoring_crhbp"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(reshape2)
library(scales)
library(ComplexHeatmap)
library(circlize)
library(googlesheets4)
library(lmerTest)
library(broom)
library(cowplot)
library(ggsci)
#library(multcomp)
library(emmeans)
source("~/nest/rstudio/utils/stats.R")
```

```{r}
data_dirs = list(tutor = "~/nest/cellprofiler/tutoring_crhbp/",
                 deaf = "~/nest/cellprofiler/deaf_crhbp/")
data_fnames = file.path(data_dirs, "analysis_channel2_cellpose.csv")
data_roi_fnames = file.path(data_dirs, "analysis_roi_object.csv")
script_name = "tutoring_crhbp_cellprofiler"
out_dir = file.path("~/nest/rstudio/neuropeptide/imaging", script_name)
dir.create(out_dir)
```

## Load metadata

```{r}
tutor_log = read_sheet("1DpJrlv7ZF7BmrUmrTMf2d2tzmoJOfBFvxYje-iLL_8I", sheet = "tutoring")
colnames(tutor_log) = make.names(tolower(colnames(tutor_log)))
tutor_log = tutor_log %>%
  rename(condition = day.group) %>%
  mutate(expt = "tutor")
  

deaf_log = read_sheet("1bP9dB_vkqKVtx5wvpRe6zbSvbZjQSBSYCw83OCv0dWg", sheet = "log")
colnames(deaf_log) = make.names(tolower(colnames(deaf_log)))
deaf_log = deaf_log %>%
  mutate(condition = case_when(procedure %in% c("skin cut only", "none", "membrane removed") ~ "hearing",
                               procedure %in% c("cochlea removal") ~ "deaf")) %>%
  mutate(expt = "deaf")

log = map(list(tutor_log, deaf_log), function(lo) {
  lo %>% select(bird, condition, expt)
}) %>% bind_rows()
```


## Load imaging data

```{r}
dat = map(data_fnames, function(fn) read.csv(fn)) %>% set_names(names(data_dirs)) %>%  bind_rows(.id="expt")

md = dat %>% ungroup() %>% distinct_at(vars(one_of("ImageNumber", "expt"), contains("Metadata")) ) 
colnames(md) = sub("Metadata_", "", colnames(md))
md_long = md %>% 
  #select(-slide.1) %>%  
  gather(key="variable", value="value", -slide, -ImageNumber) 

dat = dat %>%
  group_by(ImageNumber, expt) %>% 
  mutate_at(vars(contains("Intensity_")), list(scale = scale_01))

dat_long = dat %>% select_at(vars(matches("Intensity_MeanIntensity_channel[1-9]_sub_background$"), one_of(c("ImageNumber", "ObjectNumber", "expt")))) %>% 
  gather(key = "variable", value="intensity_mean", -ImageNumber, -ObjectNumber, -expt) %>%
  mutate(variable_s = map(variable, function(x) unlist(str_split(x, "_"))),
         channel = map_chr(variable_s, 3)) %>%
  select(-variable, -variable_s)
md_channels = dat %>% distinct_at(vars(matches("Metadata_channel[1-9]"), one_of("ImageNumber", "expt"))) %>%
  gather(key="variable", value="probe", -ImageNumber, -expt) %>%
  mutate(variable_s = map(variable, function(x) unlist(str_split(x, "_"))),
         channel = map_chr(variable_s, 2)) %>%
  select(-variable, -variable_s)

dat_roi = dat %>% select(ImageNumber, ObjectNumber, expt, Parent_roi_object, Metadata_region) %>%
  mutate(region = case_when(Metadata_region=="ra" & Parent_roi_object == 0 ~ "arco",
                            Metadata_region=="ra" & Parent_roi_object == 1 ~ "ra",
                            Metadata_region=="lman" & Parent_roi_object == 1 ~ "lman",
                            Metadata_region=="lman" & Parent_roi_object == 0 ~ "nr",
                            Metadata_region=="hvc" & Parent_roi_object == 1 ~ "hvc",
                            Metadata_region=="hvc" & Parent_roi_object == 0 ~ "nc"
  ))
dat_long = dat_long %>% left_join(md_channels) 
dat_long = dat_long %>% left_join(dat_roi %>% select(ImageNumber, ObjectNumber, expt, region))
```


```{r}
md = md %>% left_join(log %>% select(bird,condition, expt))
md = md %>% mutate(region = factor(region, levels=c("ra", "arco", "hvc", "nc", "lman", "nr")))
```

```{r}
dat_long = dat_long %>% left_join(md %>% select(ImageNumber, bird, condition, expt)) %>%
  filter(!is.na(condition))
dat_long = dat_long %>%  mutate(region = factor(region, levels=c("ra", "arco", "hvc", "nc", "lman", "nr"))) %>%
  mutate(condition = factor(condition, levels=c("1d", "20-21d", "hearing", "deaf")))
```

## Plotting

```{r}
tmp = dat_long %>% filter(probe=="crhbp")
gg = ggplot(tmp, aes(intensity_mean)) + 
  geom_density() + 
  facet_wrap(~region)
gg
```

```{r}
tmp = dat_long %>% filter(probe=="crhbp")
tmp_sum = tmp %>%
  group_by(bird, region, probe, condition) %>%
  summarize(intensity_mean_mean = mean(intensity_mean),
            intensity_mean_sem = sem(intensity_mean),
            intensity_mean_lower = intensity_mean_mean - intensity_mean_sem,
            intensity_mean_upper = intensity_mean_mean + intensity_mean_sem)
tmp_sum2 = tmp_sum %>%
  group_by(region, probe, condition) %>%
  summarize(intensity_mean_mean_mean = mean(intensity_mean_mean))
gg = ggplot() + 
  #geom_point(aes(condition, intensity_mean, color=bird), position=position_jitterdodge(dodge.width = .4, jitter.width = .2), alpha=.1) + 
  geom_pointrange(data=tmp_sum, 
                  aes(condition, 
                      y=intensity_mean_mean, 
                      ymin=intensity_mean_lower, 
                      ymax=intensity_mean_upper
                  ),
                  size=.1,
                  color="grey40",
                  position=position_jitter(width=.3)
  ) + 
  geom_point(data=tmp_sum2,
             aes(condition,
                 y=intensity_mean_mean_mean,
                 color=condition
             ),
             size=2
  ) + 
  scale_color_aaas() + 
  facet_wrap(~region, ncol = 2) + 
  theme_bw() + 
  theme(axis.text = element_text(size=6),
        axis.title = element_text(size=7),
        strip.text = element_text(size=7),
        legend.key.size = unit(.1, "in"))
gg
save_plot(file.path(out_dir, "points_by_condition_crhbp.pdf"), gg, nrow=3, ncol=2, base_height=1, base_asp=1.7)
```

```{r}
tmp = dat_long %>% filter(probe=="crhbp")
tmp_sum = tmp %>%
  group_by(bird, region, probe, condition) %>%
  summarize(ncells= n())
tmp_sum2 = tmp_sum %>%
  group_by(region, probe, condition) %>%
  summarize(ncells_mean = mean(ncells))
gg = ggplot() + 
  #geom_point(aes(condition, intensity_mean, color=bird), position=position_jitterdodge(dodge.width = .4, jitter.width = .2), alpha=.1) + 
  geom_point(data=tmp_sum, 
                  aes(condition, 
                      y=ncells
                  ),
                  size=.1,
                  color="grey40",
                  position=position_jitter(width=.3)
  ) + 
  geom_point(data=tmp_sum2,
             aes(condition,
                 y=ncells_mean,
                 color=condition
             ),
             size=2
  ) + 
  scale_color_aaas() + 
  facet_wrap(~region, ncol = 2) + 
  theme_bw() + 
  theme(axis.text = element_text(size=6),
        axis.title = element_text(size=7),
        strip.text = element_text(size=7),
        legend.key.size = unit(.1, "in"))
gg
save_plot(file.path(out_dir, "num-cells_points_by_condition_crhbp.pdf"), gg, nrow=3, ncol=2, base_height=1, base_asp=1.7)
```

## Summarize data

```{r}
dat_long_sum = dat_long %>% 
  group_by(condition, bird, region) %>%
  summarize(intensity_mean_mean = mean(intensity_mean),
            intensity_mean_median = median(intensity_mean),
            intensity_mean_sem = sem(intensity_mean))
  
```

```{r}
gg = ggplot(dat_long_sum, aes(condition, intensity_mean_median)) +
  geom_point(position=position_jitter(width = .2)) + 
  facet_wrap(~region, ncol=2)
gg
```

## Modeling

```{r}
dat_long = dat_long %>% 
  mutate(expt_ImageNumber = paste(expt, ImageNumber, sep="_"))
```

```{r}
do_anova = function(d, des, des0) {
  print(unique(d$bird))
  if (length(unique(d$bird)) < 2 || length(unique(d$condition)) < 2)
    return(data.frame())
  mod = lmer(des, data=d)
  mod0 = lmer(des0, data=d)
  return(tidy(anova(mod, mod0)))
}

#cl = makeCluster(8)
do_pb = function(d) {
  print(unique(d$bird))
  print(head(d))
  if (length(unique(d$bird)) < 2 || length(unique(d$condition)) < 2)
    return(data.frame())
  
  mod = lmer(des, data=d)
  mod0 = lmer(des0, data=d)
  t = summary(PBmodcomp(mod, mod0, seed = 1, cl = cl, details=1))$test
  t = t %>% rownames_to_column(var="test")
  return(t)
}


```

```{r}
des = intensity_mean ~ condition + (1 |  bird / expt_ImageNumber)
des0 = intensity_mean ~ (1 | bird)
```

```{r}
pairs = combn(unique(dat_long$condition), 2, simplify = F)
names(pairs) = map_chr(pairs, function(x) paste(x, collapse="_"))
```

```{r}
coef_ims = map_dfr(seq_along(pairs), function(i) {
  
  pa = pairs[[i]]
  coef_im = dat_long %>% filter(condition %in% pa) %>% group_by(probe, region) %>% do({
    d = .
    mod = lmerTest::lmer(des, d)
    co = summary(mod)$coefficients %>% as.data.frame() %>%
      rownames_to_column(var="coef") %>%
      mutate(p.value =  `Pr(>|t|)`)
    co
  }) %>% 
    mutate(pair = names(pairs)[i])
  
  coef_im1 = na.omit(coef_im)
  coef_im1 = coef_im1 %>% mutate(p.value1 = cut(p.value,
                                              breaks=c(0, .001, .01, .05, 1),
                                              labels = c( "p < .001",
                                                          "p < .01",
                                                          "p < .05",
                                                          "NS" )
                                              ),
                               p.value2 = sprintf("p = %s", round(p.value, 3)))
})
coef_ims %>% filter(probe=="crhbp", grepl("condition", coef)) %>% select(region, pair, p.value)
```

```{r}
# coef_ims = map_dfr(seq_along(pairs), function(i) {
#   
#   pa = pairs[[i]]
#   coef_im = dat_long %>% filter(condition %in% pa) %>% group_by(probe, region) %>% do({
#     d = .
#    do_anova(d, des, des0)
#   }) %>% 
#     mutate(pair = names(pairs)[i])
#   
#   coef_im1 = na.omit(coef_im)
#   coef_im1 = coef_im1 %>% mutate(p.value1 = cut(p.value,
#                                               breaks=c(0, .001, .01, .05, 1),
#                                               labels = c( "p < .001",
#                                                           "p < .01",
#                                                           "p < .05",
#                                                           "NS" )
#                                               ),
#                                p.value2 = sprintf("p = %s", round(p.value, 3)))
# })
# coef_ims %>% filter(probe=="crhbp") %>% select(region, pair, p.value)
```

```{r}
des = intensity_mean ~ condition + (1 |  bird)
coefs_ims = dat_long %>%
  group_by(probe, region) %>%
  do({
    tmp = .
    
    #tmp = dat_long %>% filter(probe=="crhbp", region=="ra")
    mod = lmer(des, data=tmp)
    res_sum = emmeans(mod, list(pairwise ~ condition), adjust = "tukey") %>% summary() 
    co = res_sum$`pairwise differences of condition` %>% as.data.frame() %>%
      rename(pair = `1`)
    co
  })

print(coefs_ims)
#summary(glht(model, linfct = mcp(condition = "Tukey")), test = adjusted("holm"))
```

```{r}
fw = facet_wrap(~region, scales="free", ncol = 2)
colors = scale_color_brewer(palette="Dark2")
th =  theme_bw() + theme(strip.text.y = element_text(angle=0),
                  axis.text.x = element_text(angle=45, hjust=1))
#yl =  ylim(0, 180)
lb = labs(x = "", y = "Mean intensity")

for (p in unique(dat_long$probe)) {
  tmp = dat_long %>%
    filter(probe==p) %>% 
    mutate(condition = factor(condition, levels=c("1d", "20-21d", "hearing", "deaf"), 
                              labels=c("40 dph", "60 dph", "adult - hearing", "adult - deaf")))
  
  gg = ggplot(tmp, aes(condition, intensity_mean)) + 
    geom_point(position=position_jitter(width=.2), alpha=.2) +
    stat_summary(fun.data = "mean_se", position=position_dodge(width=.6), shape=21, fill="black", size=.5, width=0) +
    th + 
    #yl + 
    lb +
    fw + 
    labs(title=p)

  #df1 <- data.frame(a = c(.9, .9, 1.1,1.1), b = c(100, 105, 105, 100), condition="Deaf", probe="CRHBP", nucleus2="RA")
  #gg = gg + geom_text(data = datas2 %>% ungroup() %>% 
  #                      distinct(probe, nucleus2,.keep_all=T), 
  #                    aes(label=p.value1), y = 150, color="black")
  #gg = gg + geom_text(data = datas2 %>% ungroup() %>%
  #                     distinct(probe, nucleus2,.keep_all=T),
  #                   aes(label=p.value2), y = 150, color="black")
  print(gg)
  save_plot(paste(out_dir, sprintf("probe_intensity_no-song-split_%s.pdf", p), sep="/"), base_height=1, base_asp=1.4)
  
}
```

## Number of cells

```{r}
dat_rois = map(data_roi_fnames, read.csv) %>% set_names(names(data_dirs)) %>% bind_rows(.id="expt")
dat_long = dat %>% select_at(vars(matches("Intensity_MeanIntensity_channel[1-9]_sub_background$"), one_of(c("ImageNumber", "ObjectNumber", "expt")))) %>% 
  gather(key = "variable", value="intensity_mean", -ImageNumber, -ObjectNumber, -expt) %>%
  mutate(variable_s = map(variable, function(x) unlist(str_split(x, "_"))),
         channel = map_chr(variable_s, 3)) %>%
  select(-variable, -variable_s)
md_channels = dat %>% distinct_at(vars(matches("Metadata_channel[1-9]"), one_of("ImageNumber", "expt"))) %>%
  gather(key="variable", value="probe", -ImageNumber, -expt) %>%
  mutate(variable_s = map(variable, function(x) unlist(str_split(x, "_"))),
         channel = map_chr(variable_s, 2)) %>%
  select(-variable, -variable_s)

dat_roi = dat %>% select(ImageNumber, ObjectNumber, expt, Parent_roi_object, Metadata_region) %>%
  mutate(region = case_when(Metadata_region=="ra" & Parent_roi_object == 0 ~ "arco",
                            Metadata_region=="ra" & Parent_roi_object == 1 ~ "ra",
                            Metadata_region=="lman" & Parent_roi_object == 1 ~ "lman",
                            Metadata_region=="lman" & Parent_roi_object == 0 ~ "nr",
                            Metadata_region=="hvc" & Parent_roi_object == 1 ~ "hvc",
                            Metadata_region=="hvc" & Parent_roi_object == 0 ~ "nc"
  ))
dat_long = dat_long %>% left_join(md_channels) 
dat_long = dat_long %>% left_join(dat_roi %>% select(ImageNumber, ObjectNumber, expt, region))
```
